# PyTorch


In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

## Basic


In [4]:
a = torch.tensor([2, 2], dtype=int)
print(a)

b = torch.tensor([2.3, 2.2], dtype=float)
print(b)

b = torch.tensor([2.3, 2.2], dtype=torch.float64)
print(b)

tensor([2, 2])
tensor([2.3000, 2.2000], dtype=torch.float64)
tensor([2.3000, 2.2000], dtype=torch.float64)


In [8]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(tensor.ndim, tensor.shape, tensor.size(), tensor.dtype)

2 torch.Size([2, 3]) torch.Size([2, 3]) torch.int64


## Random
