# PyTorch


In [39]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

import numpy as np

## Basic


In [40]:
a = torch.tensor([2, 2], dtype=int)
print(a)

b = torch.tensor([2.3, 2.2], dtype=float)
print(b)

b = torch.tensor([2.3, 2.2], dtype=torch.float64)
print(b)

print(a[0])
print(a[0].item())

tensor([2, 2])
tensor([2.3000, 2.2000], dtype=torch.float64)
tensor([2.3000, 2.2000], dtype=torch.float64)
tensor(2)
2


In [41]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(tensor.ndim, tensor.shape, tensor.size(), tensor.dtype)

2 torch.Size([2, 3]) torch.Size([2, 3]) torch.int64


## Random


In [42]:
print(torch.arange(10))
print(torch.arange(0, 10, 2))

print(torch.zeros(10))
print(torch.zeros((2, 10)))

print(torch.ones(10))
print(torch.ones((2, 10)))

print(torch.eye(4))
print(torch.eye(4, 4))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [43]:
np1 = torch.rand(3, 4)  # random number between 0 and 1
print(np1)

print("----------------")
np2 = torch.randn(2, 3)  # apply normal distribution to the random number
print(np2)

print("----------------")
np3 = torch.randint(0, 10, (2, 3))
print(np3)

print("----------------")
array = torch.tensor([[1, 2, 3], [4, 5, 6]])
np5 = torch.rand_like(array, dtype=float)
print(np5)

tensor([[0.4707, 0.4484, 0.0124, 0.3219],
        [0.1917, 0.3647, 0.9613, 0.2486],
        [0.1576, 0.0975, 0.2882, 0.2892]])
----------------
tensor([[-0.9447,  2.0613,  0.6884],
        [ 0.9965,  0.1748, -0.1849]])
----------------
tensor([[1, 1, 5],
        [4, 4, 4]])
----------------
tensor([[0.3149, 0.9730, 0.2150],
        [0.5886, 0.8337, 0.8688]], dtype=torch.float64)


## Reshape


In [44]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor1 = tensor.reshape(3, 2)
tensor2 = tensor.view(3, 2)
print(tensor1)
print(tensor2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Numpy & PyTorch Convertion


In [46]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

np1 = np.array(tensor)
print(np1)

tensor1 = torch.tensor(np1)
print(tensor1)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
