# PyTorch


In [65]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

import numpy as np

## Basic


In [66]:
a = torch.tensor([2, 2], dtype=int)
print(a)

b = torch.tensor([2.3, 2.2], dtype=float)
print(b)

b = torch.tensor([2.3, 2.2], dtype=torch.float64)
print(b)

print(a[0])
print(a[0].item())

tensor([2, 2])
tensor([2.3000, 2.2000], dtype=torch.float64)
tensor([2.3000, 2.2000], dtype=torch.float64)
tensor(2)
2


In [67]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(tensor.ndim, tensor.shape, tensor.size(), tensor.dtype)

2 torch.Size([2, 3]) torch.Size([2, 3]) torch.int64


## Random


In [68]:
print(torch.arange(10))
print(torch.arange(0, 10, 2))

print(torch.zeros(10))
print(torch.zeros((2, 10)))

print(torch.ones(10))
print(torch.ones((2, 10)))

print(torch.eye(4))
print(torch.eye(4, 4))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [69]:
np1 = torch.rand(3, 4)  # random number between 0 and 1
print(np1)

print("----------------")
np2 = torch.randn(2, 3)  # apply normal distribution to the random number
print(np2)

print("----------------")
np3 = torch.randint(0, 10, (2, 3))
print(np3)

print("----------------")
array = torch.tensor([[1, 2, 3], [4, 5, 6]])
np5 = torch.rand_like(array, dtype=float)
print(np5)

tensor([[0.3999, 0.1860, 0.2425, 0.3464],
        [0.7281, 0.3721, 0.0709, 0.0387],
        [0.6604, 0.8347, 0.9147, 0.6240]])
----------------
tensor([[1.3843, 2.0249, 0.7583],
        [0.7585, 0.3194, 0.6708]])
----------------
tensor([[5, 6, 7],
        [4, 1, 5]])
----------------
tensor([[0.7962, 0.9661, 0.6524],
        [0.4053, 0.9883, 0.7275]], dtype=torch.float64)


## Reshape


In [70]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor1 = tensor.reshape(3, 2)
tensor2 = tensor.view(3, 2)
print(tensor1)
print(tensor2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Numpy & PyTorch Convertion


In [71]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

np1 = np.array(tensor)
print(np1)

tensor1 = torch.tensor(np1)
print(tensor1)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


## Calculation


In [72]:
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
result = torch.tensor([])

print(tensor1 + tensor2)
print(torch.add(tensor1, tensor2, out=result))
print("result", result)

print("----------------")
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor3.add_(tensor2)  # inplace operation
print(tensor3)

print("----------------")
print(tensor1 - tensor2)
print(torch.sub(tensor1, tensor2))

print("----------------")
print(tensor1 * tensor2)
print(torch.mul(tensor1, tensor2))

print("----------------")
print(tensor1 / tensor2)
print(torch.div(tensor1, tensor2))

print("----------------")
tensor4 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=float)
tensor5 = torch.tensor([[7, 8], [9, 10], [11, 12]], dtype=float)
tensor6 = torch.matmul(tensor4, tensor5)  # matrix multiplication
print(tensor6)
print(tensor6.T)
tensor4 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=float)
tensor5 = torch.tensor([[7, 8, 10]], dtype=float)
tensor7 = torch.dot(tensor4[0], tensor5[0])  # dot is only for 1D tensor
print(tensor7)

print("----------------")
print(torch.sum(tensor4))
print(torch.min(tensor4))
print(torch.max(tensor4))
print(torch.mean(tensor4, dtype=float))  # average
print(torch.argmax(tensor4))  # index of maximum value
print(torch.argmin(tensor4))  # index of minimum value

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
result tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
----------------
tensor([[ 8, 10, 12],
        [14, 16, 18]])
----------------
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
----------------
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
----------------
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
----------------
tensor([[ 58.,  64.],
        [139., 154.]], dtype=torch.float64)
tensor([[ 58., 139.],
        [ 64., 154.]], dtype=torch.float64)
tensor(53., dtype=torch.float64)
----------------
tensor(21., dtype=torch.float64)
tensor(1., dtype=torch.float64)
tensor(6., dtype=torch.float64)
tensor(3.5000, dtype=torch.float64)
tensor(5)
tensor(0)


## Gradient


In [73]:
x = torch.ones(2, 2, requires_grad=True)
print(tensor)

y = x + 2
print(y)

z = y * y * 3
print(z)

out = z.mean()
print(out)

out.backward()
print(tensor.grad)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
None
