# Numpy

## Import

In [147]:
import numpy as np

## Create & Type

In [148]:
# Create a numpy array
np1 = np.array([0, 1, 2, 3, 4, 5, 6])
print(np1)
# Print the array
print(np1.shape)

# Create a numpy array
my_list = [0, 1, 2, 3, 4, 5, 6]
np2 = np.array(my_list)

print(np2.dtype)

[0 1 2 3 4 5 6]
(7,)
int64


## Common ways to create array

In [149]:
print(np.arange(10))
print(np.arange(0, 10, 2))

print(np.zeros(10))
print(np.zeros((2, 10)))

print(np.ones(10))
print(np.ones((2, 10)))

print(np.full((10), 6))
print(np.full((2, 10), 6))

print(np.eye(4))
print(np.eye(4, 4))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Random

In [150]:
# random
np1 = np.random.random((2, 10))
print(np1)

np2 = np.random.randint(0, 10, (2, 10))
print(np2)

[[0.25875642 0.53622734 0.53484999 0.34747067 0.85822675 0.08780566
  0.59943701 0.72780378 0.34487122 0.56095524]
 [0.05265132 0.2903262  0.99918863 0.22958261 0.29658646 0.42737711
  0.02606663 0.19742626 0.25168967 0.56750066]]
[[0 7 7 6 7 8 1 5 8 4]
 [5 2 5 5 0 2 1 8 8 1]]


## Dimension

In [151]:
# ndim & shape & size & itemsize
np1 = np.random.randint(0, 10, 10)
print(np1)
print(np1.ndim)
print(np1.shape)
print(np1.size)
print(np1.itemsize)

print('----------------')
np2 = np.random.randint(0, 10, (2, 10))
print(np2)
print(np2.ndim)
print(np2.shape)
print(np2.size)
print(np2.itemsize)

print('----------------')
np3 = np.random.randint(0, 10, (2, 3, 4))
print(np3)
print(np3.ndim)
print(np3.shape)
print(np3.size)
print(np3.itemsize)

[7 5 0 0 7 3 8 0 2 3]
1
(10,)
10
8
----------------
[[2 8 7 9 9 4 3 8 4 6]
 [2 8 8 9 5 1 4 2 6 4]]
2
(2, 10)
20
8
----------------
[[[0 7 5 5]
  [8 4 3 7]
  [5 5 6 3]]

 [[1 0 1 0]
  [0 0 5 4]
  [6 1 3 2]]]
3
(2, 3, 4)
24
8


In [152]:
# reshape
np1 = np.random.randint(0, 10, 20)
print(np1, np1.shape)

print('----------------')
np2 = np1.reshape(2, 10)
print(np2, np2.shape)

print('----------------')
np3 = np1.reshape(2, 2, 5)
print(np3, np3.shape)

# -1 means let numpy figure out the dimension size in that dimension
print('----------------')
np4 = np3.reshape((-1, 1))
print(np4, np4.shape)

# -1 means let numpy figure out the dimension size in that dimension
print('----------------')
np5 = np3.reshape((1, -1))
print(np5, np5.shape)

print('----------------')
np6 = np3.flatten() # flatten() always returns a copy
print(np6, np6.shape)

print('----------------')
np7 = np3.ravel() # ravel() returns a view if possible
print(np7, np7.shape)


[5 7 5 1 6 5 1 2 6 7 5 2 6 6 8 6 6 1 4 6] (20,)
----------------
[[5 7 5 1 6 5 1 2 6 7]
 [5 2 6 6 8 6 6 1 4 6]] (2, 10)
----------------
[[[5 7 5 1 6]
  [5 1 2 6 7]]

 [[5 2 6 6 8]
  [6 6 1 4 6]]] (2, 2, 5)
----------------
[[5]
 [7]
 [5]
 [1]
 [6]
 [5]
 [1]
 [2]
 [6]
 [7]
 [5]
 [2]
 [6]
 [6]
 [8]
 [6]
 [6]
 [1]
 [4]
 [6]] (20, 1)
----------------
[[5 7 5 1 6 5 1 2 6 7 5 2 6 6 8 6 6 1 4 6]] (1, 20)
----------------
[5 7 5 1 6 5 1 2 6 7 5 2 6 6 8 6 6 1 4 6] (20,)


## Slice

In [153]:
# Slice in one dimension
np1 = np.arange(10)
print(np1)

print(np1[4])
print(np1[0:4])
print(np1[0:10:2])

[0 1 2 3 4 5 6 7 8 9]
4
[0 1 2 3]
[0 2 4 6 8]


In [154]:
# Slice in two dimension
np2 = np.arange(24).reshape(4, 6)
print(np2)

print('----------------')
print(np2[0])
print(np2[0, 0])

print('----------------')
print(np2[0:1, :])
print(np2[:, 0])
print(np2[0:2, 0:3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[0 1 2 3 4 5]
0
----------------
[[0 1 2 3 4 5]]
[ 0  6 12 18]
[[0 1 2]
 [6 7 8]]


## Bool Index

In [155]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1 < 10
print(np2)

print('----------------')
np3 = np1[np1 < 10]
print(np3)

print('----------------')
np4 = np1[np1 % 2 == 0]
print(np4)

print('----------------')
np5 = np1[(np1 < 5) & (np1 > 10)]
print(np5)

print('----------------')
np6 = np1[(np1 < 5) | (np1 > 10)]
print(np6)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]
----------------
[0 1 2 3 4 5 6 7 8 9]
----------------
[ 0  2  4  6  8 10 12 14 16 18 20 22]
----------------
[]
----------------
[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Value Update

In [156]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np1[0] = 100
print(np1)

print('----------------')
np1[np1 < 10] = 0
print(np1)

print('----------------')
np2 = np.where(np1 > 20, 0, 1)
print(np2)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[100 100 100 100 100 100]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
----------------
[[100 100 100 100 100 100]
 [  0   0   0   0  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
----------------
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 0 0 0]]


## Broadcast

In [157]:
# array and number
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1 + 10
print(np2)

print('----------------')
np3 = np1 * 10
print(np3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]
----------------
[[  0  10  20  30  40  50]
 [ 60  70  80  90 100 110]
 [120 130 140 150 160 170]
 [180 190 200 210 220 230]]


In [158]:
# array and array
np1 = np.arange(24).reshape(4, 6)
print(np1)

# shape must be the same
print('----------------')
np2 = np.arange(24).reshape(4, 6) 
print(np1 + np2) 

# row is the same
print('----------------')
np3 = np.arange(4).reshape(-1, 1)
print(np3)
print(np1 + np3)

# column is the same
print('----------------')
np4 = np.arange(6)
print(np4)
print(np1 + np4)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
----------------
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]
----------------
[0 1 2 3 4 5]
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]


## Arrays Concatenate

In [159]:
# row
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np.arange(12).reshape(-1, 6)
print(np2)

np3 = np.vstack((np1, np2))
print(np3)

# column
print('----------------')
np4 = np.arange(24).reshape(4, 6)
print(np4)
np5 = np.arange(12).reshape(4, -1)
print(np5)

np6 = np.hstack((np4, np5))
print(np6)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  0  1  2]
 [ 6  7  8  9 10 11  3  4  5]
 [12 13 14 15 16 17  6  7  8]
 [18 19 20 21 22 23  9 10 11]]


In [160]:
# concatenate

# column
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np.arange(12).reshape(4, -1)
print(np2)

np3 = np.concatenate((np1, np2), axis=1)
print(np3)

# row
print('----------------')
np4 = np.arange(24).reshape(4, 6)
print(np4)
np5 = np.arange(12).reshape(-1, 6)
print(np5)

np6 = np.concatenate((np4, np5), axis=0)
print(np6)

# flatten
print('----------------')
np7 = np.concatenate((np4, np5), axis=None)
print(np7)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  0  1  2]
 [ 6  7  8  9 10 11  3  4  5]
 [12 13 14 15 16 17  6  7  8]
 [18 19 20 21 22 23  9 10 11]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
----------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  0  1  2  3  4  5  6  7  8  9 10 11]


## Array Split

In [161]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
v1, v2 = np.vsplit(np1, 2)
print(v1, v2)

print('----------------')
v1, v2, v3, v4 = np.vsplit(np1, 4)
print(v1, v2, v3, v4)

print('----------------')
h1, h2 = np.hsplit(np1, 2)
print(h1, h2)

print('----------------')
h1, h2, h3 = np.hsplit(np1, 3)
print(h1, h2, h3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[0 1 2 3 4 5]] [[ 6  7  8  9 10 11]] [[12 13 14 15 16 17]] [[18 19 20 21 22 23]]
----------------
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]] [[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]
----------------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


In [162]:
# array_split
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
v1, v2 = np.array_split(np1, 2, axis=0)
print(v1, v2)

print('----------------')
v1, v2, v3 = np.array_split(np1, 3, axis=1)
print(v1, v2, v3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


## Array Transpose

In [166]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1.T
print(np2)

print('----------------')
np3 = np1.transpose()
print(np3)

print('----------------')
np4 = np1.dot(np2)
print(np4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
----------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
----------------
[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


## Array Copy

In [168]:
# no copy
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np1
print(np2)

print('----------------')
np2[0, 0] = 1
print(np1, np2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [169]:
# shallow copy
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np1.view()
print(np2)

print('----------------')
np2[0, 0] = 1
print(np1, np2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [170]:
# deep copy
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np1.copy()
print(np2)

print('----------------')
np2[0, 0] = 1
print(np1, np2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
