# Numpy

## Import

In [109]:
import numpy as np

## Create & Type

In [110]:
# Create a numpy array
np1 = np.array([0, 1, 2, 3, 4, 5, 6])
print(np1)
# Print the array
print(np1.shape)

# Create a numpy array
my_list = [0, 1, 2, 3, 4, 5, 6]
np2 = np.array(my_list)

print(np2.dtype)

[0 1 2 3 4 5 6]
(7,)
int64


## Common ways to create array

In [111]:
print(np.arange(10))
print(np.arange(0, 10, 2))

print(np.zeros(10))
print(np.zeros((2, 10)))

print(np.ones(10))
print(np.ones((2, 10)))

print(np.full((10), 6))
print(np.full((2, 10), 6))

print(np.eye(4))
print(np.eye(4, 4))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [112]:
# random
np1 = np.random.random((2, 10))
print(np1)

np2 = np.random.randint(0, 10, (2, 10))
print(np2)

[[9.11937663e-01 2.15213555e-02 1.96080142e-01 6.60533049e-01
  8.57140513e-01 4.00181114e-01 1.43960469e-01 1.15593379e-01
  6.42018994e-01 3.84239730e-01]
 [5.49609525e-01 2.97508073e-01 3.94471612e-01 4.11012614e-01
  9.16335257e-01 9.39958801e-01 1.10893123e-02 6.94818258e-01
  5.46673621e-01 7.38798009e-04]]
[[7 3 1 7 7 4 3 4 3 1]
 [4 0 1 9 7 4 7 0 8 1]]


## Dimension

In [113]:
# ndim & shape & size & itemsize
np1 = np.random.randint(0, 10, 10)
print(np1)
print(np1.ndim)
print(np1.shape)
print(np1.size)
print(np1.itemsize)

print('----------------')
np2 = np.random.randint(0, 10, (2, 10))
print(np2)
print(np2.ndim)
print(np2.shape)
print(np2.size)
print(np2.itemsize)

print('----------------')
np3 = np.random.randint(0, 10, (2, 3, 4))
print(np3)
print(np3.ndim)
print(np3.shape)
print(np3.size)
print(np3.itemsize)

[7 7 4 0 1 3 4 4 2 2]
1
(10,)
10
8
----------------
[[7 0 0 1 8 9 0 3 5 9]
 [2 2 0 7 3 7 7 7 7 5]]
2
(2, 10)
20
8
----------------
[[[8 8 6 7]
  [6 4 0 1]
  [1 7 7 8]]

 [[9 4 2 0]
  [2 3 8 3]
  [2 1 3 0]]]
3
(2, 3, 4)
24
8


In [114]:
# reshape
np1 = np.random.randint(0, 10, 20)
print(np1, np1.shape)

print('----------------')
np2 = np1.reshape(2, 10)
print(np2, np2.shape)

print('----------------')
np3 = np1.reshape(2, 2, 5)
print(np3, np3.shape)

# -1 means let numpy figure out the dimension size in that dimension
print('----------------')
np4 = np3.reshape((-1, 1))
print(np4, np4.shape)

# -1 means let numpy figure out the dimension size in that dimension
print('----------------')
np5 = np3.reshape((1, -1))
print(np5, np5.shape)

print('----------------')
np6 = np3.flatten() # flatten() always returns a copy
print(np6, np6.shape)

print('----------------')
np7 = np3.ravel() # ravel() returns a view if possible
print(np7, np7.shape)


[6 3 2 8 9 2 2 2 2 0 7 8 1 2 3 1 0 9 7 6] (20,)
----------------
[[6 3 2 8 9 2 2 2 2 0]
 [7 8 1 2 3 1 0 9 7 6]] (2, 10)
----------------
[[[6 3 2 8 9]
  [2 2 2 2 0]]

 [[7 8 1 2 3]
  [1 0 9 7 6]]] (2, 2, 5)
----------------
[[6]
 [3]
 [2]
 [8]
 [9]
 [2]
 [2]
 [2]
 [2]
 [0]
 [7]
 [8]
 [1]
 [2]
 [3]
 [1]
 [0]
 [9]
 [7]
 [6]] (20, 1)
----------------
[[6 3 2 8 9 2 2 2 2 0 7 8 1 2 3 1 0 9 7 6]] (1, 20)
----------------
[6 3 2 8 9 2 2 2 2 0 7 8 1 2 3 1 0 9 7 6] (20,)
----------------
[6 3 2 8 9 2 2 2 2 0 7 8 1 2 3 1 0 9 7 6] (20,)


## Slice

In [115]:
# Slice in one dimension
np1 = np.arange(10)
print(np1)

print(np1[4])
print(np1[0:4])
print(np1[0:10:2])

[0 1 2 3 4 5 6 7 8 9]
4
[0 1 2 3]
[0 2 4 6 8]


In [116]:
# Slice in two dimension
np2 = np.arange(24).reshape(4, 6)
print(np2)

print('----------------')
print(np2[0])
print(np2[0, 0])

print('----------------')
print(np2[0:1, :])
print(np2[:, 0])
print(np2[0:2, 0:3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[0 1 2 3 4 5]
0
----------------
[[0 1 2 3 4 5]]
[ 0  6 12 18]
[[0 1 2]
 [6 7 8]]


## Bool Index

In [117]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1 < 10
print(np2)

print('----------------')
np3 = np1[np1 < 10]
print(np3)

print('----------------')
np4 = np1[np1 % 2 == 0]
print(np4)

print('----------------')
np5 = np1[(np1 < 5) & (np1 > 10)]
print(np5)

print('----------------')
np6 = np1[(np1 < 5) | (np1 > 10)]
print(np6)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]
----------------
[0 1 2 3 4 5 6 7 8 9]
----------------
[ 0  2  4  6  8 10 12 14 16 18 20 22]
----------------
[]
----------------
[ 0  1  2  3  4 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Value Update

In [118]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np1[0] = 100
print(np1)

print('----------------')
np1[np1 < 10] = 0
print(np1)

print('----------------')
np2 = np.where(np1 > 20, 0, 1)
print(np2)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[100 100 100 100 100 100]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
----------------
[[100 100 100 100 100 100]
 [  0   0   0   0  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
----------------
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 0 0 0]]


## Broadcast

In [119]:
# array and number
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1 + 10
print(np2)

print('----------------')
np3 = np1 * 10
print(np3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]
----------------
[[  0  10  20  30  40  50]
 [ 60  70  80  90 100 110]
 [120 130 140 150 160 170]
 [180 190 200 210 220 230]]


In [120]:
# array and array
np1 = np.arange(24).reshape(4, 6)
print(np1)

# shape must be the same
print('----------------')
np2 = np.arange(24).reshape(4, 6) 
print(np1 + np2) 

# row is the same
print('----------------')
np3 = np.arange(4).reshape(-1, 1)
print(np3)
print(np1 + np3)

# column is the same
print('----------------')
np4 = np.arange(6)
print(np4)
print(np1 + np4)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
----------------
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]
----------------
[0 1 2 3 4 5]
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]


## Arrays Concatenate

In [121]:
# row
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np.arange(12).reshape(-1, 6)
print(np2)

np3 = np.vstack((np1, np2))
print(np3)

# column
print('----------------')
np4 = np.arange(24).reshape(4, 6)
print(np4)
np5 = np.arange(12).reshape(4, -1)
print(np5)

np6 = np.hstack((np4, np5))
print(np6)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  0  1  2]
 [ 6  7  8  9 10 11  3  4  5]
 [12 13 14 15 16 17  6  7  8]
 [18 19 20 21 22 23  9 10 11]]


In [122]:
# concatenate

# column
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np.arange(12).reshape(4, -1)
print(np2)

np3 = np.concatenate((np1, np2), axis=1)
print(np3)

# row
print('----------------')
np4 = np.arange(24).reshape(4, 6)
print(np4)
np5 = np.arange(12).reshape(-1, 6)
print(np5)

np6 = np.concatenate((np4, np5), axis=0)
print(np6)

# flatten
print('----------------')
np7 = np.concatenate((np4, np5), axis=None)
print(np7)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  0  1  2]
 [ 6  7  8  9 10 11  3  4  5]
 [12 13 14 15 16 17  6  7  8]
 [18 19 20 21 22 23  9 10 11]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
----------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  0  1  2  3  4  5  6  7  8  9 10 11]


## Array Split

In [123]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
v1, v2 = np.vsplit(np1, 2)
print(v1, v2)

print('----------------')
v1, v2, v3, v4 = np.vsplit(np1, 4)
print(v1, v2, v3, v4)

print('----------------')
h1, h2 = np.hsplit(np1, 2)
print(h1, h2)

print('----------------')
h1, h2, h3 = np.hsplit(np1, 3)
print(h1, h2, h3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[0 1 2 3 4 5]] [[ 6  7  8  9 10 11]] [[12 13 14 15 16 17]] [[18 19 20 21 22 23]]
----------------
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]] [[ 3  4  5]
 [ 9 10 11]
 [15 16 17]
 [21 22 23]]
----------------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


In [124]:
# array_split
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
v1, v2 = np.array_split(np1, 2, axis=0)
print(v1, v2)

print('----------------')
v1, v2, v3 = np.array_split(np1, 3, axis=1)
print(v1, v2, v3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]] [[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]] [[ 4  5]
 [10 11]
 [16 17]
 [22 23]]


## Array Transpose

In [125]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1.T
print(np2)

print('----------------')
np3 = np1.transpose()
print(np3)

print('----------------')
np4 = np1.dot(np2)
print(np4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
----------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
----------------
[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


## Array Copy

In [126]:
# no copy
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np1
print(np2)

print('----------------')
np2[0, 0] = 1
print(np1, np2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [127]:
# shallow copy
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np1.view()
print(np2)

print('----------------')
np2[0, 0] = 1
print(np1, np2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [128]:
# deep copy
np1 = np.arange(24).reshape(4, 6)
print(np1)
np2 = np1.copy()
print(np2)

print('----------------')
np2[0, 0] = 1
print(np1, np2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 1  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## CSV

In [129]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np.savetxt('np1.csv', np1, fmt='%d', delimiter=',', header='column1, column2, column3, column4, column5, column6', comments='') 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------


In [130]:
file = np.loadtxt('np1.csv', dtype=np.int32, delimiter=',', skiprows=1)
print(file)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [131]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np.save('np1', np1) 
np.savez('np1', np1) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------


In [132]:
np1 = np.load('np1.npy')
print(np1)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## Handle Empty Value

In [133]:
np1 = np.arange(24).reshape(4, 6);
print(np1)

print('----------------')
np1 = np1.astype(float)
print(np1[0, 1])
np1[0, 1] = np.NaN

print(np1[0,1] == np.NaN) # False, because NaN is not equal to anything, including itself
print(np.isnan(np1[0,1]))
print(np1[0,1] * 2) # NaN, because any operation with NaN will result in NaN

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
1.0
False
True
nan


In [134]:
# When reading from a file, you can use the following code to convert empty strings to NaN
scores = np.genfromtxt('scores.csv', delimiter=',', missing_values='', filling_values='nan')
print(scores)
scores = scores.astype(float)

[[nan nan nan nan nan nan]
 [ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan 10. 11.]
 [12. nan 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


## Random Module

In [191]:
np.random.seed(1) # if you want the same random number, you can use the same seed
np1 = np.random.rand()
print(np1)

print('----------------')
np2 = np.random.rand(2, 3)
print(np2)

print('----------------')
np3 = np.random.randn(2, 3) # apply normal distribution to the random number
print(np3)

print('----------------')
np4 = np.random.randint(0, 10, (2, 3))
print(np4)

print('----------------')
data = [2, 4, 6, 8, 10]
np5 = np.random.choice(data, (2, 3)) # randomly select from the data
print(np5)

print('----------------')
np6 = np.arange(10)
print(np6)
np.random.shuffle(np6) # shuffle the data
print(np6)

0.417022004702574
----------------
[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]
----------------
[[-1.10593508 -1.65451545 -2.3634686 ]
 [ 1.13534535 -1.01701414  0.63736181]]
----------------
[[2 4 7]
 [7 9 1]]
----------------
[[2 4 4]
 [4 4 2]]
----------------
[0 1 2 3 4 5 6 7 8 9]
[6 4 7 9 2 3 5 0 8 1]


## Axis

In [198]:
np1 = np.arange(24).reshape(4, 6)
print(np1)

print('----------------')
np2 = np1.sum(axis=0)
print(np2)
np3 = np1.sum(axis=1)
print(np3)

print('----------------')
np4 = np1.max(axis=0)
print(np4)
np5 = np1.max(axis=1)
print(np5)

print('----------------')
np6 = np.delete(np1, 0, axis=0)
print(np6)

np7 = np.delete(np1, 1, axis=1)
print(np7)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
----------------
[36 40 44 48 52 56]
[ 15  51  87 123]
----------------
[18 19 20 21 22 23]
[ 5 11 17 23]
----------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  2  3  4  5]
 [ 6  8  9 10 11]
 [12 14 15 16 17]
 [18 20 21 22 23]]
